#!/usr/bin/env python
"""Simple script to just get the port for an ip or mac and print it"""

from netdisco import db
import ieeemac

def get_port(q):
    if ieeemac.ismac(q):
        func = db.Port.get_by_mac
    else:
        func = db.Port.get_by_ip

    port = func(q)
    return port

if __name__ == "__main__":
    import sys
    q = sys.argv[1]
    print get_port(q)

