#!/usr/bin/env python


import sys
from netdisco import db

def getallips(ciscoonly=False):
    return db.util.get_all_ips(ciscoonly)


def filter(nodes, q):
    for ip, name in nodes:
        if not name:
            name=''
        if not q or (q in ip or q.lower() in name.lower()):
            yield ip, name
        
if __name__ == "__main__":
    filt = None
    if len(sys.argv) > 1:
        filt = sys.argv[1:]

    nodes = getallips()
    while filt:
        nodes = filter(nodes, filt[0])
        filt = filt[1:]
    
    for ip, name in nodes:
        print ip, name
